networks:
    laravel:
        driver: bridge

volumes:
    db_data:


services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.3-fpm
        container_name: laravel_inertia_react # container name
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            db:
                condition: service_healthy
        networks:
            - laravel
        command: php-fpm

    web:
        image: nginx:alpine
        container_name: laravel_web
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: laravel_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        networks:
            - laravel
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 3s
            timeout: 5s
            retries: 10

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: rootpassword
        networks:
            - laravel
